# -*- coding: utf-8 -*-
"""House Prices_base.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n9iA_8KcBPDuuxy7dWyJT_Ui4DGdP-qU

if house pricing was as easy as a house costs 50k + 50k per bedroom, so that a 1 bedroom house costs 100k, a 2 bedroom house costs 150k.

creating a neural network that learns this relationship so that it would predict a 7 bedroom house as costing close to 400k etc.
"""

import tensorflow as tf
import numpy as np
from tensorflow import keras

model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

model.compile(optimizer='sgd', loss='mean_squared_error')

xs = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 10.0], dtype=float)
ys = np.array([100.0, 150.0, 200.0, 250.0, 300.0, 350.0, 550.0], dtype=float)

model.fit(xs, ys, epochs=500)
    
print(model.predict([7.0]))

print('A house with %d bedrooms will worth about %fk' % (7, model.predict([7.0])))